name: Libva Windows
on:
  push:
    paths:
      - .github/workflows/windows-action.yml      
jobs:
  libva:
    name: Libva Build
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        sys: [mingw64, msvc]
        architecture: [x86_64]
    steps:
      - uses: actions/checkout@v3
      - id: libva_compose
        uses: lab-github/libva@libva-actions
        with:
          sys: ${{matrix.sys}}
          architecture: ${{matrix.architecture}}
